# Invoking: appgen_module TMbase X 
# Invoking: appgen_module Sonic X Suffix=1 mode=csat3
# Invoking: appgen_module Sonic X Suffix=2 mode=csat3b
# Invoking: appgen_module Zeno X mode=default
# Makefile Generated Wed Jun 01 21:11:24 EDT 2016
MNC=GCToF
SPECFILE=GCToF.spec
PCMFILE=GCToF.pcm
SRC=types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc
SRC+=IG.tmc UPS.tmc SWData.tmc SWData.h freemem.tmc sonic1.tmc
SRC+=sonic2.tmc TwisTorr_conv.tmc nXDS_conv.tmc Horiba_conv.tmc
SRC+=GCToF.tbl nXDS.tbl sonic.tbl UPS.tbl GCToF.tma GCToF.sws
SRC+=GCToF.doit TwisTorr.cmd nXDS.cmd zaber.cmd Horiba.cmd SWData.cmd
SRC+=TwisTorr_col.tmc nXDS_col.tmc Horiba_col.tmc UPS_col.tmc
SRC+=SWData_col.tmc sonic1_col.tmc sonic2_col.tmc GCToF.genui
SRC+=TMbase.genui sonic1.genui sonic2.genui Zeno.genui
TOOL=GCToF.spec Makefile
SCRIPT=interact
OBJ=SWData.cmd SWData.h SWData.tmc SWData_col.tmc GCToFtbl.tmc
OBJ+=nXDStbl.tmc sonictbl.tmc UPStbl.tmc GCToFdisp.cc GCToFdispoui.c
OBJ+=GCToFdispoui.o GCToFdisp.o GCToFtblnc.tmc nXDStblnc.tmc
OBJ+=sonictblnc.tmc UPStblnc.tmc GCToFdispnc.cc GCToFdispncoui.c
OBJ+=GCToFdispncoui.o GCToFdispnc.o GCToFsws.tma GCToFalgoa.tmc
OBJ+=GCToFalgo.cc GCToFalgooui.c GCToFalgooui.o GCToFalgo.o doit.dep
OBJ+=GCToFcmd.cc GCToFcmd.dat GCToFclt.o GCToFcltoui.c GCToFcltoui.o
OBJ+=GCToFcltnc.o GCToFcltncoui.c GCToFcltncoui.o GCToFsrvr.o
OBJ+=GCToFsrvroui.c GCToFsrvroui.o GCToFcol.cc GCToF.pcm tm.dac
OBJ+=GCToFcoloui.c GCToFcoloui.o GCToFcol.o GCToFengext.cdf
OBJ+=GCToFengextcdf.oui GCToFengextcdf.tmc GCToFengext.cc
OBJ+=GCToFengextoui.c GCToFengextoui.o GCToFengext.o GCToFtbl.tmc.dep
OBJ+=nXDStbl.tmc.dep sonictbl.tmc.dep UPStbl.tmc.dep
OBJ+=GCToFtblnc.tmc.dep nXDStblnc.tmc.dep sonictblnc.tmc.dep
OBJ+=UPStblnc.tmc.dep
TGT=GCToFdisp GCToFdispnc GCToFalgo doit GCToFclt GCToFcltnc
TGT+=GCToFsrvr GCToFcol GCToFengext
DISTRIB=../Sonic/TM/../sonic ../Sonic/TM/../sonic_csat3b
DISTRIB+=../Zeno/TM/../Zeno_Ser ../Agilent/TwisTorr ../Edwards/nXDS
DISTRIB+=../Horiba/horiba ../IonGauge/IonGauge ../Zaber/zaber
DISTRIB+=../UPS/ups GCToF.pcm tm.dac
IDISTRIB=Experiment.config VERSION doit
SRCDIST=GCToF.tbl nXDS.tbl sonic.tbl UPS.tbl GCToF.tma types.tmc
SRCDIST+=base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc
SRCDIST+=UPS.tmc SWData.tmc SWData.h
SRCDIST+=/usr/local/share/huarp/tdrift.tmc
SRCDIST+=/usr/local/share/huarp/cpu_usage.tmc
SRCDIST+=/usr/local/share/huarp/tmdf.tmc freemem.tmc
SRCDIST+=/usr/local/share/huarp/flttime.tmc
SRCDIST+=../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc
SRCDIST+=../Zeno/TM/Zeno.tmc
TMCBASE=types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc
TMCBASE+=Horiba.tmc IG.tmc UPS.tmc SWData.tmc SWData.h
TMCBASE+=/usr/local/share/huarp/tdrift.tmc
TMCBASE+=/usr/local/share/huarp/cpu_usage.tmc
TMCBASE+=/usr/local/share/huarp/tmdf.tmc freemem.tmc
TMCBASE+=/usr/local/share/huarp/flttime.tmc
TMCBASE+=../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc
TMCBASE+=../Zeno/TM/Zeno.tmc
CMDBASE=/usr/local/share/huarp/root.cmd TwisTorr.cmd nXDS.cmd
CMDBASE+=zaber.cmd Horiba.cmd ../UPS/TM/UPS.cmd SWData.cmd SWData.h
CMDBASE+=/usr/local/share/huarp/getcon.cmd ../Zeno/TM/Zeno.cmd
COLBASE=TwisTorr_col.tmc nXDS_col.tmc Horiba_col.tmc UPS_col.tmc
COLBASE+=SWData_col.tmc /usr/local/share/huarp/tdrift_col.tmc
COLBASE+=/usr/local/share/huarp/cpu_usage_col.tmc
COLBASE+=/usr/local/share/huarp/tmdf_col.tmc
COLBASE+=/usr/local/share/huarp/freemem_col.tmc sonic1_col.tmc
COLBASE+=sonic2_col.tmc ../Zeno/TM/Zeno_col.tmc
SWSBASE=GCToF.sws
QCLIBASE=
SPECDEPBASE=/usr/local/share/huarp/TMbase.agm
SPECDEPBASE+=/usr/local/share/huarp/freemem_def.tmc.in
SPECDEPBASE+=/usr/local/share/huarp/TMbase.genui.in
SPECDEPBASE+=/usr/local/share/huarp/TMbase.tbl.in
SPECDEPBASE+=../Sonic/TM/Sonic.agm ../Sonic/TM/sonic.tmc.in
SPECDEPBASE+=../Sonic/TM/sonic_col.tmc.in ../Sonic/TM/sonic.genui.in
SPECDEPBASE+=../Sonic/TM/sonic.tbl.in ../Sonic/TM/sonic3B.tmc.in
SPECDEPBASE+=../Zeno/TM/Zeno.agm ../Zeno/TM/Zeno.genui.in
SPECDEPBASE+=../Zeno/TM/Zeno.tbl.in
AG_CPPFLAGS=-I ../Sonic/TM/.. -I ../Sonic/TM/.. -I ../Zeno/TM/..
PHTGT=GCToFtbl.tmc nXDStbl.tmc sonictbl.tmc UPStbl.tmc
RCS=$(SRC) $(TOOL) $(SCRIPT)
SOURCE=$(RCS) $(NONRCS)
OBJECT=$(OBJ) *.err
TARGET=$(TGT)
DSTRB=$(TGT) $(DISTRIB) $(SCRIPT)
TGTDIR= $(TGTNODE)/home/GCToF
include /usr/local/share/huarp/appgen.mk

.PHONY : all all-dist extdistribution distribution clean clean-dist check_photon

IGNOREFILE=.gitignore
all : Makefile check_photon $(TGT) $(IGNOREFILE)
all-dist : $(DSTRB) $(SRCDIST) VERSION
Makefile : GCToF.spec $(SPECDEPBASE)
	appgen GCToF.spec
VERSION=`cat VERSION`
extdistribution : $(DSTRB) $(SRCDIST) VERSION
	@[ -d $(TGTDIR)/bin ] || mkdir $(TGTDIR)/bin
	@[ -d $(TGTDIR)/bin/$(VERSION) ] || mkdir $(TGTDIR)/bin/$(VERSION)
	@[ -d $(TGTDIR)/bin/$(VERSION)/Base ] || mkdir $(TGTDIR)/bin/$(VERSION)/Base
	@[ ! -f $(TGTDIR)/bin/$(VERSION)/$(PCMFILE) ] || \
	  cmp -s $(TGTDIR)/bin/$(VERSION)/$(PCMFILE) $(PCMFILE) || \
	  ( echo "$(PCMFILE) changed without VERSION update"; false )
	@distribute $(FORCE) $(TGTDIR)/bin/$(VERSION) $(DSTRB)
	@distribute $(FORCE) $(TGTDIR)/bin/$(VERSION)/Base $(SRCDIST)
distribution : extdistribution
	@distribute $(FORCE) $(TGTDIR) $(IDISTRIB)
check_photon :
ifeq ($(WPHOTON),YES)
	@for tgt in $(PHTGT); do \
	  cmp -s $$tgt /usr/local/share/huarp/nulltbl.tmc && echo Remaking $$tgt && rm -f $$tgt; \
	done; true
endif
GCToFdisp : GCToFdisp.o GCToFdispoui.o
	$(LINK.normCXX) GCToFdisp.o GCToFdispoui.o -ldisp -ltmph -lph -ltmpp -ltm -lnort
	$(OUIUSE) GCToFdispoui.c
GCToFdispnc : GCToFdispnc.o GCToFdispncoui.o
	$(LINK.normCXX) GCToFdispnc.o GCToFdispncoui.o -ldispnc -ltmnc -lncurses -ltmpp -ltm -lnort
	$(OUIUSE) GCToFdispncoui.c
GCToFalgo : GCToFalgo.o GCToFalgooui.o
	$(LINK.normCXX) GCToFalgo.o GCToFalgooui.o -ltmpp -ltm -lnort
	$(OUIUSE) GCToFalgooui.c
doit : GCToF.doit
	mkdoit3 -o doit  GCToF.doit
GCToFclt : GCToFclt.o GCToFcltoui.o
	$(LINK.normCXX) GCToFclt.o GCToFcltoui.o -ltmph -lph -ltmpp -ltm -lnort
	$(OUIUSE) GCToFcltoui.c
GCToFcltnc : GCToFcltnc.o GCToFcltncoui.o
	$(LINK.normCXX) GCToFcltnc.o GCToFcltncoui.o -ltmnc -lncurses -ltmpp -ltm -lnort
	$(OUIUSE) GCToFcltncoui.c
GCToFsrvr : GCToFsrvr.o GCToFsrvroui.o
	$(LINK.privCXX) GCToFsrvr.o GCToFsrvroui.o -ltmpp -ltm -lnort
	$(OUIUSE) GCToFsrvroui.c
	$(PROMOTE) GCToFsrvr
GCToFcol : GCToFcol.o GCToFcoloui.o
	$(LINK.privCXX) GCToFcol.o GCToFcoloui.o -ltmpp -ltm -lnort
	$(OUIUSE) GCToFcoloui.c
	$(PROMOTE) GCToFcol
GCToFengext : GCToFengext.o GCToFengextoui.o
	$(LINK.normCXX) GCToFengext.o GCToFengextoui.o -ltmpp -ltm -lnort
	$(OUIUSE) GCToFengextoui.c
GCToFtbl.tmc : GCToF.tbl
-include GCToFtbl.tmc.dep
nXDStbl.tmc : nXDS.tbl
-include nXDStbl.tmc.dep
sonictbl.tmc : sonic.tbl
-include sonictbl.tmc.dep
UPStbl.tmc : UPS.tbl
-include UPStbl.tmc.dep
GCToFdisp.cc : types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc UPS.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc ../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc ../Zeno/TM/Zeno.tmc TwisTorr_conv.tmc nXDS_conv.tmc Horiba_conv.tmc GCToFtbl.tmc nXDStbl.tmc sonictbl.tmc UPStbl.tmc VERSION
	$(TMC) types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc UPS.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc ../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc ../Zeno/TM/Zeno.tmc TwisTorr_conv.tmc nXDS_conv.tmc Horiba_conv.tmc GCToFtbl.tmc nXDStbl.tmc sonictbl.tmc UPStbl.tmc
GCToFdispoui.c : $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
GCToFdispoui.o : GCToFdispoui.c SWData.h
GCToFdisp.o : GCToFdisp.cc SWData.h
GCToFtblnc.tmc : GCToF.tbl
-include GCToFtblnc.tmc.dep
nXDStblnc.tmc : nXDS.tbl
-include nXDStblnc.tmc.dep
sonictblnc.tmc : sonic.tbl
-include sonictblnc.tmc.dep
UPStblnc.tmc : UPS.tbl
-include UPStblnc.tmc.dep
GCToFdispnc.cc : types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc UPS.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc ../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc ../Zeno/TM/Zeno.tmc TwisTorr_conv.tmc nXDS_conv.tmc Horiba_conv.tmc GCToFtblnc.tmc nXDStblnc.tmc sonictblnc.tmc UPStblnc.tmc VERSION
	$(TMC) types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc UPS.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc ../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc ../Zeno/TM/Zeno.tmc TwisTorr_conv.tmc nXDS_conv.tmc Horiba_conv.tmc GCToFtblnc.tmc nXDStblnc.tmc sonictblnc.tmc UPStblnc.tmc
GCToFdispncoui.c : $(OUIDIR)/nctable.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/nctable.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
GCToFdispncoui.o : GCToFdispncoui.c SWData.h
GCToFdispnc.o : GCToFdispnc.cc SWData.h
GCToFsws.tma : GCToF.sws
	$(COMPILE.sws) GCToF.sws
GCToFalgoa.tmc : GCToF.tma GCToFsws.tma GCToFsrvr
	$(SERVER) ./GCToFsrvr
	$(TMCALGO) -V "`./GCToFsrvr -R`" GCToF.tma GCToFsws.tma
GCToFalgo.cc : types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc UPS.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc ../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc ../Zeno/TM/Zeno.tmc GCToFalgoa.tmc VERSION
	$(TMC) types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc UPS.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc ../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc ../Zeno/TM/Zeno.tmc GCToFalgoa.tmc
GCToFalgooui.c : $(OUIDIR)/tma.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/tma.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
GCToFalgooui.o : GCToFalgooui.c SWData.h
GCToFalgo.o : GCToFalgo.cc SWData.h
doit.dep : GCToF.doit
	mkdoit3 -M -o doit  GCToF.doit
-include doit.dep
GCToFcmd.cc : /usr/local/share/huarp/root.cmd TwisTorr.cmd nXDS.cmd zaber.cmd Horiba.cmd ../UPS/TM/UPS.cmd SWData.cmd /usr/local/share/huarp/getcon.cmd ../Zeno/TM/Zeno.cmd
	$(CMDGEN) -d GCToFcmd.dat /usr/local/share/huarp/root.cmd TwisTorr.cmd nXDS.cmd zaber.cmd Horiba.cmd ../UPS/TM/UPS.cmd SWData.cmd /usr/local/share/huarp/getcon.cmd ../Zeno/TM/Zeno.cmd
GCToFclt.o : GCToFcmd.cc SWData.h
	$(COMPILE.clt) GCToFcmd.cc
GCToFcltoui.c : $(OUIDIR)/kbdclt.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/kbdclt.oui $(OUIDIR)/msg.oui
GCToFcltoui.o : GCToFcltoui.c SWData.h
GCToFcltnc.o : GCToFcmd.cc SWData.h
	$(COMPILE.cltnc) GCToFcmd.cc
GCToFcltncoui.c : $(OUIDIR)/kbdclt.oui $(OUIDIR)/nctable.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/kbdclt.oui $(OUIDIR)/nctable.oui $(OUIDIR)/msg.oui
GCToFcltncoui.o : GCToFcltncoui.c SWData.h
GCToFsrvr.o : GCToFcmd.cc SWData.h
	$(COMPILE.srvr) GCToFcmd.cc
GCToFsrvroui.c : $(OUIDIR)/cis.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/cis.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/msg.oui
GCToFsrvroui.o : GCToFsrvroui.c SWData.h
GCToFcol.cc : types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc UPS.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc ../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc ../Zeno/TM/Zeno.tmc TwisTorr_col.tmc nXDS_col.tmc Horiba_col.tmc UPS_col.tmc SWData_col.tmc /usr/local/share/huarp/tdrift_col.tmc /usr/local/share/huarp/cpu_usage_col.tmc /usr/local/share/huarp/tmdf_col.tmc /usr/local/share/huarp/freemem_col.tmc sonic1_col.tmc sonic2_col.tmc ../Zeno/TM/Zeno_col.tmc VERSION
	$(TMC.col) types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc UPS.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc ../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc ../Zeno/TM/Zeno.tmc TwisTorr_col.tmc nXDS_col.tmc Horiba_col.tmc UPS_col.tmc SWData_col.tmc /usr/local/share/huarp/tdrift_col.tmc /usr/local/share/huarp/cpu_usage_col.tmc /usr/local/share/huarp/tmdf_col.tmc /usr/local/share/huarp/freemem_col.tmc sonic1_col.tmc sonic2_col.tmc ../Zeno/TM/Zeno_col.tmc
GCToFcoloui.c : $(OUIDIR)/collect.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/collect.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/msg.oui
GCToFcoloui.o : GCToFcoloui.c SWData.h
GCToFcol.o : GCToFcol.cc SWData.h
GCToFengext.cdf : GCToF.genui ../UPS/TM/UPS.genui ../Zaber/TM/zaber.genui TMbase.genui sonic1.genui sonic2.genui Zeno.genui
	$(GENUI2ENG) GCToF.genui ../UPS/TM/UPS.genui ../Zaber/TM/zaber.genui TMbase.genui sonic1.genui sonic2.genui Zeno.genui
GCToFengextcdf.oui : GCToFengext.cdf
	$(EDF2OUI) GCToFengext.cdf
GCToFengextcdf.tmc : GCToFengext.cdf
	$(EDF2EXT) GCToFengext.cdf
GCToFengext.cc : types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc UPS.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc ../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc ../Zeno/TM/Zeno.tmc GCToFengextcdf.tmc VERSION
	$(TMC) types.tmc base.tmc TwisTorr.tmc nXDS.tmc zaber.tmc Horiba.tmc IG.tmc UPS.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc ../Sonic/TM/sonic_types.tmc sonic1.tmc sonic2.tmc ../Zeno/TM/Zeno.tmc GCToFengextcdf.tmc
GCToFengextoui.c : GCToFengextcdf.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) GCToFengextcdf.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
GCToFengextoui.o : GCToFengextoui.c SWData.h
GCToFengext.o : GCToFengext.cc SWData.h
SWData.h SWData.tmc SWData_col.tmc SWData.cmd :  GCToF.sws
	swscomp -o SWData  GCToF.sws

tidy :
	rm -f $(OBJECT)
clean : tidy
	rm -f $(TARGET)
clean-dist : clean
$(IGNOREFILE) : Makefile
	@for i in $(OBJECT) $(TARGET); do echo "$$i"; done >$(IGNOREFILE)
../Sonic/TM/../sonic :
	cd ../Sonic/TM/.. && make sonic
.PHONY : clean-sonic
clean-dist : clean-sonic
clean-sonic :
	cd ../Sonic/TM/.. && make clean
../Sonic/TM/../sonic_csat3b :
	cd ../Sonic/TM/.. && make sonic_csat3b
.PHONY : clean-sonic3b
clean-dist : clean-sonic3b
clean-sonic3b :
	cd ../Sonic/TM/.. && make clean
../Zeno/TM/../Zeno_Ser :
	cd ../Zeno/TM/.. && make
.PHONY : clean-Zeno
clean-dist : clean-Zeno
clean-Zeno :
	cd ../Zeno/TM/.. && make clean
CPPFLAGS += -I ../Agilent -I ../Edwards -I ../Horiba -I ../IonGauge -I ../Zaber
CPPFLAGS += -I ../Sonic -I ../UPS
# CPPFLAGS += -I ../Zeno



../Agilent/TwisTorr :
	cd ../Agilent && make
../Edwards/nXDS :
	cd ../Edwards && make
../Horiba/horiba :
	cd ../Horiba && make
../IonGauge/IonGauge :
	cd ../IonGauge && make
../Zaber/zaber :
	cd ../Zaber && make
../UPS/ups :
	cd ../UPS && make
