function pGCToFsn(varargin);
% pGCToFsn( [...] );
% Sonic 1 N
h = timeplot({'Sonic1_N','Sonic1_N'}, ...
      'Sonic 1 N', ...
      'N', ...
      {'Sonic1\_N','Sonic1\_N'}, ...
      varargin{:} );
