function pGCToFgchgcb(varargin);
% pGCToFgchgcb( [...] );
% GC Horiba GC Bypass
h = timeplot({'GC_Bypass_SP','GC_Bypass'}, ...
      'GC Horiba GC Bypass', ...
      'GC Bypass', ...
      {'GC\_Bypass\_SP','GC\_Bypass'}, ...
      varargin{:} );
