function pGCToFttv(varargin);
% pGCToFttv( [...] );
% Twis Torr V
h = timeplot({'TT1_V','TT2_V','TT3_V'}, ...
      'Twis Torr V', ...
      'V', ...
      {'TT1\_V','TT2\_V','TT3\_V'}, ...
      varargin{:} );
