function pGCToFgbhs(varargin);
% pGCToFgbhs( [...] );
% GB Horiba Status
h = ne_dstat({
  'Fluorine_SP_Stat', 'GBHoribaS', 0; ...
	'Fluorine_Stat', 'GBHoribaS', 1; ...
	'IonSrc_SP_Stat', 'GBHoribaS', 2; ...
	'IonSrc_Stat', 'GBHoribaS', 3; ...
	'DilFT_SP_Stat', 'GBHoribaS', 4; ...
	'DilFT_Stat', 'GBHoribaS', 5; ...
	'CalP_SP_Stat', 'GBHoribaS', 6; ...
	'CalP_Stat', 'GBHoribaS', 7; ...
	'GBHoriba_CS', 'GBHoribaS', 10 }, 'Status', varargin{:} );
