function pGCToFtts(varargin);
% pGCToFtts( [...] );
% Twis Torr Speed
h = timeplot({'TT1_drvf','TT1_spd','TT2_drvf','TT2_spd','TT3_drvf','TT3_spd'}, ...
      'Twis Torr Speed', ...
      'Speed', ...
      {'TT1\_drvf','TT1\_spd','TT2\_drvf','TT2\_spd','TT3\_drvf','TT3\_spd'}, ...
      varargin{:} );
