function pGCToFgcwgcf4_3t(varargin);
% pGCToFgcwgcf4_3t( [...] );
% GC Watlow GCF4 3T
h = timeplot({'GCF4_3T'}, ...
      'GC Watlow GCF4 3T', ...
      'GCF4 3T', ...
      {'GCF4\_3T'}, ...
      varargin{:} );
