function pGCToFgbz(varargin);
% pGCToFgbz( [...] );
% GB Zero
h = timeplot({'MFC_AMBZ_SP','MFC_AMBZ'}, ...
      'GB Zero', ...
      'Zero', ...
      {'MFC\_AMBZ\_SP','MFC\_AMBZ'}, ...
      varargin{:} );
