function pGCToFtts(varargin);
% pGCToFtts( [...] );
% Twis Torr Speed
h = timeplot({'TT1_drvf','TT1_spd'}, ...
      'Twis Torr Speed', ...
      'Speed', ...
      {'TT1\_drvf','TT1\_spd'}, ...
      varargin{:} );
