function pGCToFsonic2stale(varargin);
% pGCToFsonic2stale( [...] );
% Sonic 2 Stale
h = timeplot({'Sonic2_Stale'}, ...
      'Sonic 2 Stale', ...
      'Stale', ...
      {'Sonic2\_Stale'}, ...
      varargin{:} );
