function pGCToFfvp(varargin);
% pGCToFfvp( [...] );
% Fly Valve Pos
h = timeplot({'FlySt','Fly_Pos_RB'}, ...
      'Fly Valve Pos', ...
      'Pos', ...
      {'FlySt','Fly\_Pos\_RB'}, ...
      varargin{:} );
