function pGCToFss(varargin);
% pGCToFss( [...] );
% Sonic 1 Sound
h = timeplot({'Sonic1_C','Sonic1_C'}, ...
      'Sonic 1 Sound', ...
      'Sound', ...
      {'Sonic1\_C','Sonic1\_C'}, ...
      varargin{:} );
