function pGCToFsonic2s(varargin);
% pGCToFsonic2s( [...] );
% Sonic 2 Sound
h = timeplot({'Sonic2_C','Sonic2_C'}, ...
      'Sonic 2 Sound', ...
      'Sound', ...
      {'Sonic2\_C','Sonic2\_C'}, ...
      varargin{:} );
