function pGCToFgcwgcpmt(varargin);
% pGCToFgcwgcpmt( [...] );
% GC Watlow GCPM6 1T
h = timeplot({'GCPM6_1T_SP','GCPM6_1T'}, ...
      'GC Watlow GCPM6 1T', ...
      'GCPM6 1T', ...
      {'GCPM6\_1T\_SP','GCPM6\_1T'}, ...
      varargin{:} );
