function pGCToFgbhstale(varargin);
% pGCToFgbhstale( [...] );
% GB Horiba Stale
h = timeplot({'GBHoriba_Stale'}, ...
      'GB Horiba Stale', ...
      'Stale', ...
      {'GBHoriba\_Stale'}, ...
      varargin{:} );
