function pGCToFgbhs(varargin);
% pGCToFgbhs( [...] );
% GB Horiba Status
h = timeplot({'GBHoribaS'}, ...
      'GB Horiba Status', ...
      'Status', ...
      {'GBHoribaS'}, ...
      varargin{:} );
