function pGCToFgcwgcft(varargin);
% pGCToFgcwgcft( [...] );
% GC Watlow GCF4 2T
h = timeplot({'GCF4_2T_SP','GCF4_2T'}, ...
      'GC Watlow GCF4 2T', ...
      'GCF4 2T', ...
      {'GCF4\_2T\_SP','GCF4\_2T'}, ...
      varargin{:} );
