function pGCToFhis(varargin);
% pGCToFhis( [...] );
% Horiba Ion Src
h = timeplot({'IonSrcFlow','IonSrcFlowSP'}, ...
      'Horiba Ion Src', ...
      'Ion Src', ...
      {'IonSrcFlow','IonSrcFlowSP'}, ...
      varargin{:} );
