function pGCToFtti(varargin);
% pGCToFtti( [...] );
% Twis Torr I
h = timeplot({'TT1_I','TT2_I','TT3_I'}, ...
      'Twis Torr I', ...
      'I', ...
      {'TT1\_I','TT2\_I','TT3\_I'}, ...
      varargin{:} );
