function pGCToFgchcn(varargin);
% pGCToFgchcn( [...] );
% GC Horiba Column N2
h = timeplot({'ColumnN2_SP','ColumnN2'}, ...
      'GC Horiba Column N2', ...
      'Column N2', ...
      {'ColumnN2\_SP','ColumnN2'}, ...
      varargin{:} );
