function pGCToFhf(varargin);
% pGCToFhf( [...] );
% Horiba Fluorine
h = timeplot({'FFlow','FFlowSP'}, ...
      'Horiba Fluorine', ...
      'Fluorine', ...
      {'FFlow','FFlowSP'}, ...
      varargin{:} );
