function pGCToFgbhdft(varargin);
% pGCToFgbhdft( [...] );
% GB Horiba Dil FT
h = timeplot({'DilFT_SP','DilFT'}, ...
      'GB Horiba Dil FT', ...
      'Dil FT', ...
      {'DilFT\_SP','DilFT'}, ...
      varargin{:} );
