function pGCToFgcwgcpm6_2t(varargin);
% pGCToFgcwgcpm6_2t( [...] );
% GC Watlow GCPM6 2T
h = timeplot({'GCPM6_2T_SP','GCPM6_2T'}, ...
      'GC Watlow GCPM6 2T', ...
      'GCPM6 2T', ...
      {'GCPM6\_2T\_SP','GCPM6\_2T'}, ...
      varargin{:} );
