function pGCToFgpsd_errtrack(varargin);
% pGCToFgpsd_errtrack( [...] );
% gpsd err track
h = timeplot({'gpsd_epd'}, ...
      'gpsd err track', ...
      'track', ...
      {'gpsd\_epd'}, ...
      varargin{:} );
