function pGCToFttstatus(varargin);
% pGCToFttstatus( [...] );
% Twis Torr Status
h = timeplot({'TT1_Status'}, ...
      'Twis Torr Status', ...
      'Status', ...
      {'TT1\_Status'}, ...
      varargin{:} );
