function pGCToFttflags(varargin);
% pGCToFttflags( [...] );
% Twis Torr flags
h = ne_dstat({
  'TT1_Start', 'TT1_flags', 0; ...
	'TT1_Speed', 'TT1_flags', 1; ...
	'TT1_WtrCl', 'TT1_flags', 2; ...
	'TT1_ActStp', 'TT1_flags', 3; ...
	'TT1_VentVlv', 'TT1_flags', 4; ...
	'TT1_VentOp', 'TT1_flags', 5 }, 'flags', varargin{:} );
