function pGCToFgchgcd(varargin);
% pGCToFgchgcd( [...] );
% GC Horiba GC Dilution
h = timeplot({'GC_Dilution_SP','GC_Dilution'}, ...
      'GC Horiba GC Dilution', ...
      'GC Dilution', ...
      {'GC\_Dilution\_SP','GC\_Dilution'}, ...
      varargin{:} );
