function pGCToFgchpf(varargin);
% pGCToFgchpf( [...] );
% GC Horiba Pickup Flow
h = timeplot({'PickupFlow_SP','PickupFlow'}, ...
      'GC Horiba Pickup Flow', ...
      'Pickup Flow', ...
      {'PickupFlow\_SP','PickupFlow'}, ...
      varargin{:} );
