function pGCToFgcwgcpmt(varargin);
% pGCToFgcwgcpmt( [...] );
% GC Watlow GCPM6 T
h = timeplot({'GCPM6_T_SP','GCPM6_T'}, ...
      'GC Watlow GCPM6 T', ...
      'GCPM6 T', ...
      {'GCPM6\_T\_SP','GCPM6\_T'}, ...
      varargin{:} );
