function pGCToFgbhis(varargin);
% pGCToFgbhis( [...] );
% GB Horiba Ion Src
h = timeplot({'IonSrc_SP','IonSrc'}, ...
      'GB Horiba Ion Src', ...
      'Ion Src', ...
      {'IonSrc\_SP','IonSrc'}, ...
      varargin{:} );
