function pGCToFupsstatw(varargin);
% pGCToFupsstatw( [...] );
% UP Sstat Warn
h = timeplot({'UPS_Warn'}, ...
      'UP Sstat Warn', ...
      'Warn', ...
      {'UPS\_Warn'}, ...
      varargin{:} );
