function pGCToFgbwgbpmt(varargin);
% pGCToFgbwgbpmt( [...] );
% GB Watlow GBPM6 2T
h = timeplot({'GBPM6_2T_SP','GBPM6_2T'}, ...
      'GB Watlow GBPM6 2T', ...
      'GBPM6 2T', ...
      {'GBPM6\_2T\_SP','GBPM6\_2T'}, ...
      varargin{:} );
