function pGCToFzs(varargin);
% pGCToFzs( [...] );
% Zaber Stale
h = timeplot({'Z1stale','Z2stale'}, ...
      'Zaber Stale', ...
      'Stale', ...
      {'Z1stale','Z2stale'}, ...
      varargin{:} );
