function pGCToFsonic2w(varargin);
% pGCToFsonic2w( [...] );
% Sonic 2 Winds
h = timeplot({'Sonic2_U','Sonic2_V','Sonic2_W','Sonic2_U','Sonic2_V','Sonic2_W'}, ...
      'Sonic 2 Winds', ...
      'Winds', ...
      {'Sonic2\_U','Sonic2\_V','Sonic2\_W','Sonic2\_U','Sonic2\_V','Sonic2\_W'}, ...
      varargin{:} );
