function pGCToFsstatus(varargin);
% pGCToFsstatus( [...] );
% Sonic 1 Status
h = timeplot({'Sonic1_S','Sonic1_S'}, ...
      'Sonic 1 Status', ...
      'Status', ...
      {'Sonic1\_S','Sonic1\_S'}, ...
      varargin{:} );
