function pGCToFsonic2n(varargin);
% pGCToFsonic2n( [...] );
% Sonic 2 N
h = timeplot({'Sonic2_N','Sonic2_N'}, ...
      'Sonic 2 N', ...
      'N', ...
      {'Sonic2\_N','Sonic2\_N'}, ...
      varargin{:} );
