function pGCToFoa(varargin);
% pGCToFoa( [...] );
% Octopole Amp
h = timeplot({'Oct_Amp_sp','Oct_Amp_RB'}, ...
      'Octopole Amp', ...
      'Amp', ...
      {'Oct\_Amp\_sp','Oct\_Amp\_RB'}, ...
      varargin{:} );
