function pGCToFgchs(varargin);
% pGCToFgchs( [...] );
% GC Horiba Status
h = ne_dstat({
  'ColumnN2_SP_Stat', 'GCHoribaS', 0; ...
	'ColumnN2_Stat', 'GCHoribaS', 1; ...
	'GC_Intake_SP_Stat', 'GCHoribaS', 2; ...
	'GC_Intake_Stat', 'GCHoribaS', 3; ...
	'PickupFlow_SP_Stat', 'GCHoribaS', 4; ...
	'PickupFlow_Stat', 'GCHoribaS', 5; ...
	'GC_Dilution_SP_Stat', 'GCHoribaS', 6; ...
	'GC_Dilution_Stat', 'GCHoribaS', 7; ...
	'GC_Bypass_SP_Stat', 'GCHoribaS', 8; ...
	'GC_Bypass_Stat', 'GCHoribaS', 9; ...
	'GCHoriba_CS', 'GCHoribaS', 10 }, 'Status', varargin{:} );
