function pGCToFttt(varargin);
% pGCToFttt( [...] );
% Twis Torr T
h = timeplot({'TT1_T','TT2_T','TT3_T'}, ...
      'Twis Torr T', ...
      'T', ...
      {'TT1\_T','TT2\_T','TT3\_T'}, ...
      varargin{:} );
