function pGCToFsstale(varargin);
% pGCToFsstale( [...] );
% Sonic 1 Stale
h = timeplot({'Sonic1_Stale'}, ...
      'Sonic 1 Stale', ...
      'Stale', ...
      {'Sonic1\_Stale'}, ...
      varargin{:} );
