function pGCToFttw(varargin);
% pGCToFttw( [...] );
% Twis Torr W
h = timeplot({'TT1_W','TT2_W','TT3_W'}, ...
      'Twis Torr W', ...
      'W', ...
      {'TT1\_W','TT2\_W','TT3\_W'}, ...
      varargin{:} );
