function pGCToFzenor(varargin);
% pGCToFzenor( [...] );
% Zeno Radiance
h = timeplot({'Zeno_SolarRadiance'}, ...
      'Zeno Radiance', ...
      'Radiance', ...
      {[0 1 -1.1 1.1 ], 'Radiance'}, ...
      varargin{:} );
