function pGCToF_gcs(varargin);
% pGCToF_gcs( [...] );
% GC Status
h = ne_dstat({
  'Bypass_Pump', 'A2_DS_A', 7; ...
	'GCsamp', 'A2_DS_A', 0; ...
	'HS_mode', 'A2_DS_A', 1; ...
	'Norm_mode', 'A2_DS_A', 2; ...
	'GC_Pickup', 'A2_DS_A', 3; ...
	'Tracer_GC', 'A2_DS_A', 4; ...
	'CO2', 'A2_DS_B', 0; ...
	'Tracer_FT', 'A2_DS_B', 1; ...
	'SpV_1', 'A2_DS_B', 2; ...
	'SpV_2', 'A2_DS_B', 3; ...
	'SpV_3', 'A2_DS_B', 4 }, 'Status', varargin{:} );
