function pGCToFts(varargin);
% pGCToFts( [...] );
% Turbo Speed
h = timeplot({'TPA_Spd','TPB_Spd'}, ...
      'Turbo Speed', ...
      'Speed', ...
      {'TPA\_Spd','TPB\_Spd'}, ...
      varargin{:} );
