function pGCToFgcwfo(varargin);
% pGCToFgcwfo( [...] );
% GC Watlow F4 Op
h = timeplot({'GCWatlow_F4_Op'}, ...
      'GC Watlow F4 Op', ...
      'F4 Op', ...
      {'GCWatlow\_F4\_Op'}, ...
      varargin{:} );
