function pGCToFzhklw(varargin);
% pGCToFzhklw( [...] );
% Zeno HK Leaf Wet
h = timeplot({'Zeno_Lightning'}, ...
      'Zeno HK Leaf Wet', ...
      'Leaf Wet', ...
      {'LeafWet'}, ...
      varargin{:} );
