function pGCToFttflags(varargin);
% pGCToFttflags( [...] );
% Twis Torr flags
h = ne_dstat({
  'TT1_Start', 'TT1_flags', 0; ...
	'TT1_Speed', 'TT1_flags', 1; ...
	'TT1_WtrCl', 'TT1_flags', 2; ...
	'TT1_ActStp', 'TT1_flags', 3; ...
	'TT1_VentVlv', 'TT1_flags', 4; ...
	'TT1_VentOp', 'TT1_flags', 5; ...
	'TT1_Resp', 'TT1_flags', 7; ...
	'TT2_Start', 'TT2_flags', 0; ...
	'TT2_Speed', 'TT2_flags', 1; ...
	'TT2_WtrCl', 'TT2_flags', 2; ...
	'TT2_ActStp', 'TT2_flags', 3; ...
	'TT2_VentVlv', 'TT2_flags', 4; ...
	'TT2_VentOp', 'TT2_flags', 5; ...
	'TT2_Resp', 'TT2_flags', 7; ...
	'TT3_Start', 'TT3_flags', 0; ...
	'TT3_Speed', 'TT3_flags', 1; ...
	'TT3_WtrCl', 'TT3_flags', 2; ...
	'TT3_ActStp', 'TT3_flags', 3; ...
	'TT3_VentVlv', 'TT3_flags', 4; ...
	'TT3_VentOp', 'TT3_flags', 5; ...
	'TT3_Resp', 'TT3_flags', 7 }, 'flags', varargin{:} );
