function pGCToFgbws(varargin);
% pGCToFgbws( [...] );
% GB Watlow Stale
h = timeplot({'GBWatlow_Stale'}, ...
      'GB Watlow Stale', ...
      'Stale', ...
      {'GBWatlow\_Stale'}, ...
      varargin{:} );
