function pGCToFgchs(varargin);
% pGCToFgchs( [...] );
% GC Horiba Status
h = timeplot({'GCHoribaS'}, ...
      'GC Horiba Status', ...
      'Status', ...
      {'GCHoribaS'}, ...
      varargin{:} );
