function pGCToFgbhf(varargin);
% pGCToFgbhf( [...] );
% GB Horiba Fluorine
h = timeplot({'Fluorine_SP','Fluorine'}, ...
      'GB Horiba Fluorine', ...
      'Fluorine', ...
      {'Fluorine\_SP','Fluorine'}, ...
      varargin{:} );
