function pGCToFzhktd(varargin);
% pGCToFzhktd( [...] );
% Zeno HK T Drift
h = timeplot({'Zeno_Tdrift'}, ...
      'Zeno HK T Drift', ...
      'T Drift', ...
      {'Zeno\_Tdrift'}, ...
      varargin{:} );
