function pGCToFhd(varargin);
% pGCToFhd( [...] );
% Horiba Dilution
h = timeplot({'DilFlow','DilFlowSP'}, ...
      'Horiba Dilution', ...
      'Dilution', ...
      {'DilFlow','DilFlowSP'}, ...
      varargin{:} );
