function pGCToFgcwgct(varargin);
% pGCToFgcwgct( [...] );
% GC Watlow GC T
h = timeplot({'GC_T_SP','GC_T'}, ...
      'GC Watlow GC T', ...
      'GC T', ...
      {'GC\_T\_SP','GC\_T'}, ...
      varargin{:} );
