function pGCToFgchstale(varargin);
% pGCToFgchstale( [...] );
% GC Horiba Stale
h = timeplot({'GCHoriba_Stale'}, ...
      'GC Horiba Stale', ...
      'Stale', ...
      {'GCHoriba\_Stale'}, ...
      varargin{:} );
