function pGCToFtc(varargin);
% pGCToFtc( [...] );
% Turbo Cmon
h = timeplot({'TPA_Cmon','TPB_Cmon'}, ...
      'Turbo Cmon', ...
      'Cmon', ...
      {'TPA\_Cmon','TPB\_Cmon'}, ...
      varargin{:} );
