function pGCToFgbwhct(varargin);
% pGCToFgbwhct( [...] );
% GB Watlow Hot Cal T
h = timeplot({'HotCalT_SP','HotCalT'}, ...
      'GB Watlow Hot Cal T', ...
      'Hot Cal T', ...
      {'HotCalT\_SP','HotCalT'}, ...
      varargin{:} );
