function pGCToFgchgci(varargin);
% pGCToFgchgci( [...] );
% GC Horiba GC Intake
h = timeplot({'GC_Intake_SP','GC_Intake'}, ...
      'GC Horiba GC Intake', ...
      'GC Intake', ...
      {'GC\_Intake\_SP','GC\_Intake'}, ...
      varargin{:} );
