function pGCToFob(varargin);
% pGCToFob( [...] );
% Octopole Bias
h = timeplot({'Oct_Bias_sp','Oct_Bias_RB'}, ...
      'Octopole Bias', ...
      'Bias', ...
      {'Oct\_Bias\_sp','Oct\_Bias\_RB'}, ...
      varargin{:} );
