function pGCToFgbs(varargin);
% pGCToFgbs( [...] );
% GB Spare
h = timeplot({'MFC_Sp1_SP','MFC_Sp1','MFC_Sp2_SP','MFC_Sp2','MFC_Sp3_SP','MFC_Sp3','MFC_Sp4_SP','MFC_Sp4','MFC_Sp5_SP','MFC_Sp5'}, ...
      'GB Spare', ...
      'Spare', ...
      {'MFC\_Sp1\_SP','MFC\_Sp1','MFC\_Sp2\_SP','MFC\_Sp2','MFC\_Sp3\_SP','MFC\_Sp3','MFC\_Sp4\_SP','MFC\_Sp4','MFC\_Sp5\_SP','MFC\_Sp5'}, ...
      varargin{:} );
