function pGCToFzhkvb(varargin);
% pGCToFzhkvb( [...] );
% Zeno HK V Batt
h = timeplot({'Zeno_VBatt'}, ...
      'Zeno HK V Batt', ...
      'V Batt', ...
      {'Zeno\_VBatt'}, ...
      varargin{:} );
