function pGCToFgcs(varargin);
% pGCToFgcs( [...] );
% Gas Cmds Status
h = ne_dstat({
  'Bypass_cal', 'Herc_DS_A', 0; ...
	'Scrub_cal', 'Herc_DS_A', 1; ...
	'H2O2_cal', 'Herc_DS_A', 2; ...
	'Oacid_cal', 'Herc_DS_A', 3; ...
	'MHP_cal', 'Herc_DS_A', 4; ...
	'Spare1_cal', 'Herc_DS_A', 5; ...
	'Spare2_cal', 'Herc_DS_A', 6; ...
	'Spare3_cal', 'Herc_DS_A', 7; ...
	'AmbZeroS', 'A1_DS_A', 0; ...
	'HotCal1S', 'A1_DS_A', 2; ...
	'HotCal2S', 'A1_DS_A', 4; ...
	'ColdCal1S', 'A1_DS_A', 6; ...
	'ColdCal2S', 'A1_DS_A', 1; ...
	'SpVlv4S', 'A1_DS_A', 3; ...
	'SpVlv5S', 'A1_DS_A', 5; ...
	'SpVlv7S', 'A1_DS_A', 7 }, 'Status', varargin{:} );
