function pGCToFsonic2status(varargin);
% pGCToFsonic2status( [...] );
% Sonic 2 Status
h = timeplot({'Sonic2_S'}, ...
      'Sonic 2 Status', ...
      'Status', ...
      {'Sonic2\_S'}, ...
      varargin{:} );
