function pGCToFgpsd_errclimb(varargin);
% pGCToFgpsd_errclimb( [...] );
% gpsd err climb
h = timeplot({'gpsd_epc'}, ...
      'gpsd err climb', ...
      'climb', ...
      {'gpsd\_epc'}, ...
      varargin{:} );
