function pGCToFgbhcp(varargin);
% pGCToFgbhcp( [...] );
% GB Horiba Cal P
h = timeplot({'CalP_SP','CalP'}, ...
      'GB Horiba Cal P', ...
      'Cal P', ...
      {'CalP\_SP','CalP'}, ...
      varargin{:} );
