function pGCToFdsdstatus(varargin);
% pGCToFdsdstatus( [...] );
% DS Daq Status
h = timeplot({'Herc_Stat','A1_Stat','A2_Stat'}, ...
      'DS Daq Status', ...
      'Status', ...
      {'Herc\_Stat','A1\_Stat','A2\_Stat'}, ...
      varargin{:} );
