function pGCToFgbt(varargin);
% pGCToFgbt( [...] );
% GB T
h = timeplot({'ColdCalT','FT_T1','FT_T2'}, ...
      'GB T', ...
      'T', ...
      {'ColdCalT','FT\_T1','FT\_T2'}, ...
      varargin{:} );
