function pGCToFgcws(varargin);
% pGCToFgcws( [...] );
% GC Watlow Stale
h = timeplot({'GCWatlow_Stale'}, ...
      'GC Watlow Stale', ...
      'Stale', ...
      {'GCWatlow\_Stale'}, ...
      varargin{:} );
