function pGCToFt_tv(varargin);
% pGCToFt_tv( [...] );
% Turbo TV
h = timeplot({'TPA_TV','TPB_TV','TPBx_TV'}, ...
      'Turbo TV', ...
      'TV', ...
      {'TPA\_TV','TPB\_TV','TPBx\_TV'}, ...
      varargin{:} );
