function pGCToFgbs(varargin);
% pGCToFgbs( [...] );
% GB Spare
h = timeplot({'MFC_Sp1_SP','MFC_SP1','MFC_Sp2_SP','MFC_SP2','MFC_Sp3_SP','MFC_SP3'}, ...
      'GB Spare', ...
      'Spare', ...
      {'MFC\_Sp1\_SP','MFC\_SP1','MFC\_Sp2\_SP','MFC\_SP2','MFC\_Sp3\_SP','MFC\_SP3'}, ...
      varargin{:} );
