function pGCToFttstale(varargin);
% pGCToFttstale( [...] );
% Twis Torr Stale
h = timeplot({'TT_stale'}, ...
      'Twis Torr Stale', ...
      'Stale', ...
      {'TT\_stale'}, ...
      varargin{:} );
