function pGCToFdsds(varargin);
% pGCToFdsds( [...] );
% DS Daq Spares
h = timeplot({'SpAO1_sp','SpAI1'}, ...
      'DS Daq Spares', ...
      'Spares', ...
      {'SpAO1\_sp','SpAI1'}, ...
      varargin{:} );
