function pGCToFtt2_errorserrors(varargin);
% pGCToFtt2_errorserrors( [...] );
% TT2 Errors errors
h = ne_dstat({
  'TT2_NoConn', 'TT2_ErrStat', 0; ...
	'TT2_PumpOT', 'TT2_ErrStat', 1; ...
	'TT2_CtrlOT', 'TT2_ErrStat', 2; ...
	'TT2_PwrFail', 'TT2_ErrStat', 3; ...
	'TT2_AuxFail', 'TT2_ErrStat', 4; ...
	'TT2_Short', 'TT2_ErrStat', 6; ...
	'TT2_OverLoad', 'TT2_ErrStat', 7; ...
	'TT2_LowBatt', 'TT2_ErrStat', 9; ...
	'TT2_BadTime', 'TT2_ErrStat', 10 }, 'errors', varargin{:} );
